/**
 * Ratings Table Schema
 * Stores user feedback and ratings for rides and the app
 */

const RatingsTableSchema = {
  tableName: 'ratings',
  
  columns: {
    // Primary Key
    id: {
      type: 'UUID',
      constraints: ['PRIMARY KEY', 'DEFAULT gen_random_uuid()'],
      purpose: 'Rating ID',
      required: true,
      autoGenerated: true
    },
    
    // Foreign Keys (Optional - can rate booking or commute session)
    booking_id: {
      type: 'UUID',
      constraints: ['FOREIGN KEY REFERENCES ride_bookings(id)'],
      purpose: 'Links to ride booking (optional)',
      required: false
    },
    
    commute_session_id: {
      type: 'UUID',
      constraints: ['FOREIGN KEY REFERENCES commute_sessions(id)'],
      purpose: 'Links to commute planning session (optional)',
      required: false
    },
    
    // Rating Fields
    app_rating: {
      type: 'INTEGER',
      constraints: ['CHECK (app_rating >= 1 AND app_rating <= 5)'],
      purpose: 'NexTransport app rating (1-5 stars)',
      required: false,
      validation: {
        min: 1,
        max: 5
      }
    },
    
    rider_rating: {
      type: 'INTEGER',
      constraints: ['CHECK (rider_rating >= 1 AND rider_rating <= 5)'],
      purpose: 'Driver rating (1-5 stars)',
      required: false,
      validation: {
        min: 1,
        max: 5
      }
    },
    
    // Feedback
    comment: {
      type: 'TEXT',
      constraints: [],
      purpose: 'User feedback and comments',
      required: false,
      validation: {
        maxLength: 1000
      }
    },
    
    // Audit Field
    created_at: {
      type: 'TIMESTAMP',
      constraints: ['DEFAULT NOW()'],
      purpose: 'Audit - rating submission time',
      required: false,
      default: 'NOW()'
    }
  },
  
  // SQL CREATE TABLE statement
  createTableSQL: `
    CREATE TABLE IF NOT EXISTS ratings (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      booking_id UUID REFERENCES ride_bookings(id),
      commute_session_id UUID REFERENCES commute_sessions(id),
      app_rating INTEGER CHECK (app_rating >= 1 AND app_rating <= 5),
      rider_rating INTEGER CHECK (rider_rating >= 1 AND rider_rating <= 5),
      comment TEXT,
      created_at TIMESTAMP DEFAULT NOW(),
      CONSTRAINT at_least_one_reference CHECK (booking_id IS NOT NULL OR commute_session_id IS NOT NULL)
    );
  `,
  
  // Indexes for performance
  indexes: [
    'CREATE INDEX IF NOT EXISTS idx_ratings_booking ON ratings(booking_id);',
    'CREATE INDEX IF NOT EXISTS idx_ratings_session ON ratings(commute_session_id);',
    'CREATE INDEX IF NOT EXISTS idx_ratings_created ON ratings(created_at);'
  ],
  
  // Additional validation notes
  notes: {
    validation: 'At least one of booking_id or commute_session_id must be provided',
    ratings: 'Both app_rating and rider_rating are optional but must be 1-5 if provided',
    comment: 'Optional feedback text, recommended max 1000 characters'
  }
};

module.exports = RatingsTableSchema;
