/**
 * Commute Sessions Table Schema
 * Stores user commute planning sessions with recommendations
 */

const SessionTableSchema = {
  tableName: 'commute_sessions',
  
  columns: {
    // Primary Key
    id: {
      type: 'UUID',
      constraints: ['PRIMARY KEY', 'DEFAULT gen_random_uuid()'],
      purpose: 'Session ID',
      required: true,
      autoGenerated: true
    },
    
    // Foreign Key
    user_id: {
      type: 'UUID',
      constraints: ['NOT NULL', 'FOREIGN KEY REFERENCES auth.users(id)'],
      purpose: 'Session owner',
      required: true
    },
    
    // Location Information (Dynamic)
    pickup: {
      type: 'TEXT',
      constraints: ['NOT NULL'],
      purpose: 'Dynamic start location (replaces home_address)',
      required: true
    },
    
    destination: {
      type: 'TEXT',
      constraints: ['NOT NULL'],
      purpose: 'Dynamic end location',
      required: true
    },
    
    // Ride Information
    ride_type: {
      type: 'TEXT',
      constraints: ['DEFAULT \'Jeepney\'', 'CHECK (ride_type IN (\'Jeepney\', \'Bus\', \'Tricycle\', \'UV Express\'))'],
      purpose: 'Type of public transport',
      required: false,
      enum: ['Jeepney', 'Bus', 'Tricycle', 'UV Express'],
      default: 'Jeepney'
    },
    
    preferred_arrival: {
      type: 'TIMESTAMP',
      constraints: [],
      purpose: 'Desired arrival time',
      required: false
    },
    
    // AI Recommendation
    recommendation: {
      type: 'TEXT',
      constraints: ['CHECK (recommendation IN (\'WAIT\', \'GO\'))'],
      purpose: 'AI recommendation: WAIT or GO',
      required: false,
      enum: ['WAIT', 'GO']
    },
    
    confidence: {
      type: 'TEXT',
      constraints: ['CHECK (confidence IN (\'High\', \'Medium\', \'Low\'))'],
      purpose: 'Confidence score of recommendation',
      required: false,
      enum: ['High', 'Medium', 'Low']
    },
    
    wait_estimate: {
      type: 'TEXT',
      constraints: [],
      purpose: 'Estimated wait time (e.g., "6-12 mins")',
      required: false
    },
    
    cost_comparison: {
      type: 'TEXT',
      constraints: [],
      purpose: 'Cost comparison (e.g., "₱12 vs ₱145")',
      required: false
    },
    
    reason: {
      type: 'TEXT',
      constraints: [],
      purpose: 'Explanation for recommendation',
      required: false
    },
    
    // User Action
    outcome: {
      type: 'TEXT',
      constraints: ['CHECK (outcome IN (\'took_ride\', \'cancelled\', \'pending\'))'],
      purpose: 'User action taken',
      required: false,
      enum: ['took_ride', 'cancelled', 'pending']
    },
    
    // Audit Field
    created_at: {
      type: 'TIMESTAMP',
      constraints: ['DEFAULT NOW()'],
      purpose: 'Audit - session creation time',
      required: false,
      default: 'NOW()'
    }
  },
  
  // SQL CREATE TABLE statement
  createTableSQL: `
    CREATE TABLE IF NOT EXISTS commute_sessions (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL REFERENCES auth.users(id),
      pickup TEXT NOT NULL,
      destination TEXT NOT NULL,
      ride_type TEXT DEFAULT 'Jeepney' CHECK (ride_type IN ('Jeepney', 'Bus', 'Tricycle', 'UV Express')),
      preferred_arrival TIMESTAMP,
      recommendation TEXT CHECK (recommendation IN ('WAIT', 'GO')),
      confidence TEXT CHECK (confidence IN ('High', 'Medium', 'Low')),
      wait_estimate TEXT,
      cost_comparison TEXT,
      reason TEXT,
      outcome TEXT CHECK (outcome IN ('took_ride', 'cancelled', 'pending')),
      created_at TIMESTAMP DEFAULT NOW()
    );
  `,
  
  // Indexes for performance
  indexes: [
    'CREATE INDEX IF NOT EXISTS idx_commute_sessions_user ON commute_sessions(user_id);',
    'CREATE INDEX IF NOT EXISTS idx_commute_sessions_created ON commute_sessions(created_at);'
  ]
};

module.exports = SessionTableSchema;
