const BookingTableSchema = {
  tableName: 'ride_bookings',
  
  columns: {
    
    id: {
      type: 'UUID',
      constraints: ['PRIMARY KEY', 'DEFAULT gen_random_uuid()'],
      purpose: 'Booking ID',
      required: true,
      autoGenerated: true
    },
    
    user_id: {
      type: 'UUID',
      constraints: ['NOT NULL', 'FOREIGN KEY REFERENCES auth.users(id)'],
      purpose: 'Passenger who made the booking',
      required: true
    },
    
    rider_id: {
      type: 'UUID',
      constraints: ['FOREIGN KEY REFERENCES user_profiles(id)'],
      purpose: 'Driver assigned to the booking',
      required: false
    },
    
    commute_session_id: {
      type: 'UUID',
      constraints: ['FOREIGN KEY REFERENCES commute_sessions(id)'],
      purpose: 'Links to commute planning session (optional)',
      required: false
    },
    
    pickup: {
      type: 'TEXT',
      constraints: ['NOT NULL'],
      purpose: 'Pickup location from commute picker',
      required: true
    },
    
    destination: {
      type: 'TEXT',
      constraints: ['NOT NULL'],
      purpose: 'Destination from commute picker',
      required: true
    },
    
    status: {
      type: 'TEXT',
      constraints: ['DEFAULT \'pending\'', 'CHECK (status IN (\'pending\', \'active\', \'completed\', \'cancelled\'))'],
      purpose: 'Current booking status',
      required: false,
      enum: ['pending', 'active', 'completed', 'cancelled'],
      default: 'pending'
    },
    
    price: {
      type: 'NUMERIC(10,2)',
      constraints: ['NOT NULL'],
      purpose: 'Ride price in PHP (e.g., ₱145)',
      required: true,
      validation: {
        min: 0
      }
    },
    
    eta_minutes: {
      type: 'INTEGER',
      constraints: [],
      purpose: 'Estimated time of arrival in minutes (e.g., 3 mins)',
      required: false,
      validation: {
        min: 0
      }
    },
    
    distance_km: {
      type: 'NUMERIC(10,2)',
      constraints: [],
      purpose: 'Distance in kilometers (e.g., 0.4 km)',
      required: false,
      validation: {
        min: 0
      }
    },
    
    created_at: {
      type: 'TIMESTAMP',
      constraints: ['DEFAULT NOW()'],
      purpose: 'Audit - booking creation time',
      required: false,
      default: 'NOW()'
    },
    
    updated_at: {
      type: 'TIMESTAMP',
      constraints: ['DEFAULT NOW()'],
      purpose: 'Audit - last status change',
      required: false,
      default: 'NOW()'
    }
  },
  
  createTableSQL: `
    CREATE TABLE IF NOT EXISTS ride_bookings (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL REFERENCES auth.users(id),
      rider_id UUID REFERENCES user_profiles(id),
      commute_session_id UUID REFERENCES commute_sessions(id),
      pickup TEXT NOT NULL,
      destination TEXT NOT NULL,
      status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),
      price NUMERIC(10,2) NOT NULL,
      eta_minutes INTEGER,
      distance_km NUMERIC(10,2),
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    );
  `,
  
  indexes: [
    'CREATE INDEX IF NOT EXISTS idx_ride_bookings_user ON ride_bookings(user_id);',
    'CREATE INDEX IF NOT EXISTS idx_ride_bookings_rider ON ride_bookings(rider_id);',
    'CREATE INDEX IF NOT EXISTS idx_ride_bookings_status ON ride_bookings(status);',
    'CREATE INDEX IF NOT EXISTS idx_ride_bookings_created ON ride_bookings(created_at);'
  ],
  
  trigger: `
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ language 'plpgsql';

    CREATE TRIGGER update_ride_bookings_updated_at BEFORE UPDATE
    ON ride_bookings FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
  `
};

module.exports = BookingTableSchema;
